In [1]:
import numpy as np

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [row,column]
print(a[1,2])
# because idx starts with zero and also use -ve idx
print(a[1,-4])

10
11


In [16]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# get a specific column
a[:,3]

array([ 4, 11])

In [18]:
#Get alittle more fancy[startidx:endidx:stepsize]
a[1,1:4:2]

array([ 9, 11])

In [19]:
a[0,2:-2:2]

array([3, 5])

In [20]:
# for changing the elements of the arrays
a[1,2] = 100
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9 100  11  12  13  14]]


In [23]:
# for changing whole column or row
a[:,1] = 50
print(a)

[[  1  50   3   4   5   6   7]
 [  8  50 100  11  12  13  14]]


3-d example

In [26]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [27]:
# Get specific Element in 3d array
#b[select in which 2d array you want to choose : in 2d array which row you want to select : in that 2d array which column you want to select]
b[:,0,0] 

array([1, 5])

In [28]:
# replace the elments
b[:,1,:] = [[9,9],[70,70]]

In [29]:
print(b)

[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [70 70]]]


Intializing Different Types of Arrays

In [33]:
# All Zeros
# inside (size of array)
np.zeros((1,2))

array([[0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
#All ones
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
# Full the Array with All other numbers
# inside this ((size of array),elemnet you want to fill the whole array)
np.full((2,3),45)

array([[45, 45, 45],
       [45, 45, 45]])

In [37]:
# Full another array with the any number
# (array_name,element)
np.full_like(a,40)

array([[40, 40, 40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40]])

In [54]:
# or 
np.full(a.shape,50)

array([[50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50]])

In [55]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.23713158, 0.55374572, 0.80460144],
       [0.71825834, 0.80432638, 0.09151377]])

In [56]:
# if you pass the array and than generate random decimal numbers
np.random.random_sample(a.shape)

array([[0.41959669, 0.88056444, 0.1877321 , 0.70832943, 0.82253031,
        0.79395678, 0.08667068],
       [0.43354357, 0.64546544, 0.66852849, 0.86100595, 0.44248489,
        0.56705328, 0.87117409]])

In [73]:
# Random integer value
np.random.randint(5,size=(2,4)) # here 5 is range of numbers in this the random nubers can between 0 to 4 , 5 not included

array([[0, 0, 0, 3],
       [4, 3, 0, 4]], dtype=int32)

In [74]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Repeat an array
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,2,axis=0)
print(r1) # completed till (31:34) by keith Galli

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [50]:
# first way to make an array which is given
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
output[1:4:1,1:4:1]=0
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
#second way to make an array which is given
# after making ones array
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [65]:
# copy 9 in zeros array
zeros[1,1]=9
print(zeros)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [67]:
# copy zeros in ones array which named as output
output[1:4,1:4]=zeros
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be Carefull When Copying Arrays

In [68]:
a = np.array([1,2,3])
#copy the array a in b
b = a
print(b)

[1 2 3]


In [69]:
#change the b array value
b[0] = 150
b

array([150,   2,   3])

In [70]:
# now again print a
a

array([150,   2,   3])

In [72]:
# we can see we are changing in b array but it also changes the value of a array
# so for stoping this 
b=a.copy()
b[0] = 500
b

array([500,   2,   3])

In [73]:
a # .copy() function stops the change ment in original array

array([150,   2,   3])

MATHEMATICS

In [74]:
a1 = np.array([1,2,3]) 
a1

array([1, 2, 3])

In [75]:
a1+2

array([3, 4, 5])

In [76]:
a1-2

array([-1,  0,  1])

In [77]:
a1*2

array([2, 4, 6])

In [78]:
a1/2

array([0.5, 1. , 1.5])

In [85]:
b = np.array([1,2,1])
a1+b

array([2, 4, 4])

In [86]:
a1 ** b

array([1, 4, 3])

In [89]:
# tAKE THE SIN and COS or other angles
np.sin(a)

array([-0.71487643,  0.90929743,  0.14112001])

##### Linear Algebra

In [95]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [97]:
np.matmul(a,b)  # multiply multipliv=cation of two matrix

array([[6., 6.],
       [6., 6.]])

In [104]:
# find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)  # getting the determinant of the matrix

# for more linear algebra function https://numpy.org/doc/stable/reference/generated/numpy.inner.html visit this link

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

##### Statistics

In [107]:
shape = np.array([[1,2,3],[4,5,6]])
shape

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
np.min(shape)

np.int64(1)

In [109]:
np.max(shape)

np.int64(6)

In [110]:
np.sum(shape)

np.int64(21)

In [111]:
np.sum(shape,axis=0) # sum of all columns

array([5, 7, 9])

In [113]:
np.sum(shape,axis=1) # sum of all rows

array([ 6, 15])

##### Reorganizing Arrays

In [115]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [117]:
print(before.shape)

(2, 4)


In [119]:
after = before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [121]:
# Vertically stacking vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
# np.vstack([v1,v2])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3]])

In [124]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous 
#### Load Data From  Files

In [129]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]], dtype=int32)

#### Boolean masking and advanced indexing

In [130]:
filedata>20

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True]])

In [131]:
# accessing values
filedata[filedata>20]

array([21, 22, 23, 24, 25, 26, 27], dtype=int32)

In [134]:
# you can access element with a list by index
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]  # index passes in the list

array([2, 3, 9])

In [137]:
# apply boolean with any funx=ction
np.any(filedata>21,axis=0)

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [139]:
np.all(filedata>5,axis=0)

array([False, False, False, False, False,  True,  True,  True,  True])

In [140]:
((filedata>15) & (filedata<21))

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False, False]])

In [141]:
~((filedata>15) & (filedata<21))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True]])

In [149]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [151]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [156]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [157]:
a[0:6:4,3:5]

array([[ 4,  5],
       [24, 25]])

In [160]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

# Numpy Tutorials Completed