In [1]:
import numpy as np

In [27]:
# creating arrays
a = np.array([1,2,3],dtype="int32")
print(a)        # we can change the dtype of array by giving above command
a

[1 2 3]


array([1, 2, 3], dtype=int32)

In [28]:
# for 2d arrays
b = np.array([[8.0,9.0,5.0],[5,6,7]])   # for creating nD arrays put a list inside a list
print(b) 

[[8. 9. 5.]
 [5. 6. 7.]]


In [29]:
# Get Dimension
a.ndim

1

In [30]:
b.ndim

2

In [31]:
# Get shape
a.shape

(3,)

In [32]:
b.shape

(2, 3)

In [33]:
# Get type
a.dtype

dtype('int32')

In [34]:
b.dtype

dtype('float64')

In [35]:
# Get size
a.itemsize

4

In [36]:
b.itemsize

8

In [37]:
#Get total size
a.nbytes

12

In [38]:
b.nbytes

48

In [39]:
# Get total items
a.size

3

In [40]:
b.size

6